site: "{{ cookiecutter.fabric_site }}"
image: "default_ubuntu_22"
slice_name: "{{ cookiecutter.project_slug }}_slice"
nodes:
  - name: "sender_node"
    count: 1
    cores: 2
    ram: 4
  - name: "worker_nodes"
    count: 3
    cores: 2
    ram: 4
  - name: "receiver_node"
    count: 1
    cores: 2
    ram: 4
network:
  - NIC_model: "NIC_Basic"
    service_type: "L2Bridge"
    service_name: "l2bridge_{{cookiecutter.project_slug}}"
    subnet: "10.0.0.0/24"
